import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'

// const roboto = Roboto({ weight: ["400", "500", "700"], subsets: ['latin'] })
const roboto = Roboto({ weight: ["400", "500", "700"], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tailwind ui component',
  description: 'Generated by Md. Nurudidn Adnan',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
